### ISSUE TITLE
Some of the native Java methods are not tagged

### ISSUE THREAD

**Issue by heroinsoul** [Programming-Systems-Lab/phosphor#24]
Hi 

I'm using automatic taint analysis with the following taint-sinks file's content:

```
java/io/DataOutputStream.incCount(I)V
java/io/DataOutputStream.writeFloat(F)V
java/io/DataOutputStream.writeBoolean(Z)V
java/io/DataOutputStream.writeByte(I)V
java/io/DataOutputStream.writeShort(I)V
java/io/DataOutputStream.writeLong(J)V
java/io/DataOutputStream.writeDouble(D)V
java/io/DataOutputStream.writeChars(Ljava/lang/String;)V
java/io/DataOutputStream.size()I
java/io/DataOutputStream.write([BII)V
java/io/DataOutputStream.write(I)V
java/io/DataOutputStream.flush()V
java/io/DataOutputStream.writeInt(I)V
java/io/DataOutputStream.writeChar(I)V
java/io/DataOutputStream.writeBytes(Ljava/lang/String;)V
java/io/DataOutputStream.writeUTF(Ljava/lang/String;)V
java/io/DataOutputStream.writeUTF(Ljava/lang/String;Ljava/io/DataOutput;)I
```

When I instrument the JRE using this file Phosphor tags most of the mentioned methods but for some reason leaves others untagged.

Here is the output I get while instrumenting JRE (Oracle JVM 8) with Phosphor and -multiTaint enabled

```
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeObjectOverride(Ljava/lang/Object;)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.annotateClass(Ljava/lang/Class;)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.close()V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.drain()V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.flush()V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.replaceObject(Ljava/lang/Object;)Ljava/lang/Object;
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.reset()V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.write$$PHOSPHORTAGGED([Ledu/columbia/cs/psl/phosphor/runtime/Taint;[B)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.write$$PHOSPHORTAGGED([Ledu/columbia/cs/psl/phosphor/runtime/Taint;[BLedu/columbia/cs/psl/phosphor/runtime/Taint;ILedu/columbia/cs/psl/phosphor/runtime/Taint;I)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.write$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;I)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeBoolean$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;Z)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeByte$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;I)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeBytes(Ljava/lang/String;)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeChar$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;I)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeChars(Ljava/lang/String;)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeDouble$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;D)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeFloat$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;F)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeInt$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;I)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeLong$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;J)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeShort$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;I)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeStreamHeader()V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeUTF(Ljava/lang/String;)V
```

Methods like 
```
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeBytes(Ljava/lang/String;)V
Sink: com/sun/corba/se/impl/io/IIOPOutputStream.writeChars(Ljava/lang/String;)V
```
were not tagged as well as other 'close' 'drain' or 'flush' methods.

I wonder what is the reason of that and if I can somehow force Phosphor to tag the specific sink.

Thanks

**Comment by jon-bell** [comment]
If a method has a primitive parameter or return type, then Phosphor needs to change the method descriptor to pass taint tags around. If a method object type parameters (e.g. String), then the taint tags will be passed as part of those objects. 

If Phosphor has to change the descriptor of a method, then to make sure that the new method doesn't collide with an existing one (possible if you were using int tags), it appends the suffix $$PHOSPHORTAGGED to the method name. For simplicity, it doesn't change the name of a method if it doesn't need to change the method descriptor for that method - it just adds all of the instrumentation into that method.

I understand that this convention can be somewhat confusing, but basically here is the deal: every single method is modified to track taint tags (unless you are peaking into the partial instrumentation branch which is its own story). If a method has a primitive or primitive array as a parameter or return type, then it's renamed and instrumented, and a stub is left behind with the old name and old parameters which simply calls the correct method (needed when native code calls into Java code). If a method does not have a primitive or primitive array as a parameter or return type, then it's instrumented without being renamed.

You can check out what happens by disassembling the instrumented bytecode using javap (if you are trying to look at code in the JRE rt.jar, then make sure to use javap -bootclasspath path/to/instrumented/rt.jar).
