### ISSUE TITLE
java.lang.NoSuchMethodError when instrumenting with obj tag instrumented JRE

### ISSUE THREAD

**Issue by heroinsoul** [Programming-Systems-Lab/phosphor#25]
Hi

When running my instrumented app with obj tag instrumented JRE I get the following error:
Exception in thread "main" java.lang.NoSuchMethodError:
 ```
java.lang.Integer.toString$$PHOSPHORTAGGED(II)Ljava/lang/String;
	at BoxClient.outputData(BoxClient.java:22)
	at BoxClient.main(BoxClient.java:53)
```

On the other hand if I use int tag instrumented JRE, instrumentation goes fine. But I need the obj tag one since I operate with objects in my app.

This error has been mentioned [here](https://github.com/Programming-Systems-Lab/phosphor/issues/1#issuecomment-165751662) but that was for instrumentation with API and I'm using automatic one. 

I instrument my JRE (oracle 8) using these commands
```
java -Xmx6g -jar target/Phosphor-0.0.2-SNAPSHOT.jar -multiTaint -forceUnboxAcmpEq -withEnumsByValue $JAVA_HOME target/jre-inst-obj
chmod +x target/jre-inst-obj/bin/*
```
It finishes successfully without any errors. 

The app I'm trying to run has the following code
import java.io.*;

```
public class BoxClient {

	public static int getData() {
		int record = 111;
		return record;
	}
	
	public static void outputData() {
		int record = getData(); 
		String line = Integer.toString(record);
		System.out.println(line);
		//System.out.println(record);


		try {
			// create a new OutputStreamWriter
			OutputStream os = new FileOutputStream("output.txt");
			DataOutputStream dos = new DataOutputStream(os);
			OutputStreamWriter writer = new OutputStreamWriter(os);
			String recordText = record + "\n";
		
			for(int index=0; index<recordText.length(); index++)
				writer.write(recordText.charAt(index));
			// flush the stream
			writer.flush();
			writer.close();
		
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
	
	public static void main(String args[]) {
		try {
			outputData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```

I'd really appreciate any advise or comment on this matter. Thanks

**Comment by heroinsoul** [comment]
The application code has to be instrumented with Phosphor using the same flags as the ones used while instrumenting the JRE, specifically -multiTaint for object tags

**Comment by jon-bell** [comment]
Yes. This is intentional. Do you mind sending a PR to update the documentation to be clearer on this fact?

**Comment by heroinsoul** [comment]
Yep, I was thinking of doing that, but maybe creating a wiki page describing the whole process is better? I can do both

**Comment by jon-bell** [comment]
Either or both is fine.
