### ISSUE TITLE
String concatenation wrapper method

### ISSUE THREAD

**Issue by heroinsoul** [Programming-Systems-Lab/phosphor#27]
Hi Jon,

Similarly to the previous issue #26 there is one more wrapper method Phosphor doesn't seem to track. 

The taint tag is discarded when the tainted variable is concatenated to the string, i.e.

`String str = tainted_int + "\n";`

In this case if tainted_int variable would initially have a taint, an empty string str concatenated with the value of this variable would not have any taint and can be further used to reveal private data. 

I'm sorry for reporting so many issues lately, but I'm using Phosphor for the project I'm working on as part of my PhD and it seems to be a perfect candidate for what I need. So now I just want to make sure it covers most of the possible ways of revealing user private data.

**Comment by jon-bell** [comment]
This is a little more sticky of a point for me. The new object itself won't have a taint, but the underlying char array should be tainted on those characters. In general, our rule is that when you make a new object, there is no way to force that objects taint tag to be anything in particular (at least through data flow). But you could propagate tags as you set that objects fields (which we do). 

One workaround would be to have an option where setting the taint of an object's field will cause that object to be tainted as well - but I think that that is a slippery slope - it's unclear how recursive that should be. 

What do you think about this when thinking about it in this light?

And no problem for the issues - it's my fault for not having solved them already :)

**Comment by heroinsoul** [comment]
Current approach seems to be right. I'm not sure if suggested workaround would generate more or less false positives. Here I trust your experience and knowledge. 

However, coming back to the original issue, the resulting char array seems to be not tainted either. So if I go ahead and print every single char from the `str` string like this:
```
for(int index=0; index<str.length(); index++) {
	System.out.println(str.charAt(index));
}
```
and specify `println` method as an illegal sink, Phosphor doesn't throw an exception. 

Full code is below:

```
public static int getData() {
	return 111;
}

public static void outputData() {
	int tainted_int = getData();
	String str = tainted_int + "\n";
	for(int index=0; index<str.length(); index++) {
		System.out.println(str.charAt(index));
	}
}

```

**Comment by jon-bell** [comment]
Ah... There was a glitch in the int-tags handling of setting taint on strings, I think. This should now be fixed with a test case. If you find another problem, adding a test case that shows the failing case would be very helpful (using the taint API rather than the auto taint/taint check).
