### ISSUE TITLE
The deps seem to be recorded in lbl after writing to array

### ISSUE THREAD

**Issue by mikefhsu** [Programming-Systems-Lab/phosphor#31]
On the lazy-arrays branch, the dependencies of array elements seem to recorded in its label, not deps.

Assume int i (lbl = i) and int[] arr (lbl = arr) are tainted.
`arr[0] = i + 9;`
`Taint t = MultiTainter.getTaint(arr[0]);`

The expected deps of t should be [i]? Currently the label i is recorded in t's label.

**Comment by jon-bell** [comment]
As discussed this is intentional.
