### ISSUE TITLE
Concatenate string with int

### ISSUE THREAD

**Issue by mikefhsu** [Programming-Systems-Lab/phosphor#35]
If I concatenate a string, say "abc", with an int, say 98, what should be the taint of its concatenation "abc98"? Seem to be a tricky case. Currently, each char in "abc98" inherits the taint from int 98. Is it possible to make "abc" in "abc98" having the taint from "abc" string and "98" in "abc98" having the taint from 98? I attach my test case for your reference:
[StringIntTest.txt](https://github.com/Programming-Systems-Lab/phosphor/files/492094/StringIntTest.txt)

Thanks.

**Comment by jon-bell** [comment]
The previous fix for handling string concat of primitives wasn't quite right. This should do it.
