### ISSUE TITLE
Imprecision about implicit tracking

### ISSUE THREAD

**Issue by BihuanChen** [Programming-Systems-Lab/phosphor#37]
Hi,

I ran Phosphor with control flow tracking enabled on the following program. 
It seems strange to me that `result1` got both `a` 's and `b`'s tags.
```java
public static int test2(int a, int b) {
	a = MultiTainter.taintedInt(a, 1);
	b = MultiTainter.taintedInt(b, 2);
	int result1 = 0;
	int result2 = 0;
	for (int i = 0; i < a; i++) {
		result1 += 1;
		for (int j = 0; j < b; j++) {
			result2 += 1;
		}
	}
	System.out.println(MultiTainter.getTaint(result1));
	System.out.println(MultiTainter.getTaint(result2));
	return result1 + result2;
}
```
Is this the expected behavior which is caused by the known imprecision problem of implicit tracking?

**Comment by jon-bell** [comment]
Yeah - I'm not sure of any way to get around this. Basically, consider what this compiles into:

`
 public testNestedLoop(IIII)V throws java/lang/Exception 
   L0
    LINENUMBER 41 L0
    ICONST_0
    ISTORE 5
   L1
    GOTO L2
   L3
    LINENUMBER 42 L3
   FRAME APPEND [I]
    IINC 1 1
   L4
    LINENUMBER 43 L4
    ICONST_0
    ISTORE 6
   L5
    GOTO L6
   L7
    LINENUMBER 44 L7
   FRAME APPEND [I]
    IINC 4 1
   L8
    LINENUMBER 43 L8
    IINC 6 1
   L6
   FRAME SAME
    ILOAD 6
    ILOAD 3
    IF_ICMPLT L7
   L9
    LINENUMBER 41 L9
    IINC 5 1
   L2
   FRAME CHOP 1
    ILOAD 5
    ILOAD 2
    IF_ICMPLT L3
   L10
    LINENUMBER 49 L10
    RETURN
`

If you consider the CFG, there only node that is post-dominated by the second jump (just before L10) is the RETURN statement. So, that's when we stop considering the impact of b on STOREs.
