### ISSUE TITLE
Error "java.lang.IllegalArgumentException:" when in selective instrument mode

### ISSUE THREAD

**Issue by jianyu-m** [Programming-Systems-Lab/phosphor#40]
Hello,

When I am using selective instrument mode in one of my sample program, it shows error:
```
java.lang.IllegalArgumentException: Got Ledu/columbia/cs/psl/phosphor/struct/LazyCharArrayIntTags; but have {V=0, Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithIntTag;=1}
```

My program is as follow:
```
        String a = "Hello";
        a.toCharArray();
```

I find out that when the return type is array then this error will show up. I am wondering if there are any way to resolve this?

Thanks a lot!

**Comment by jon-bell** [comment]
The selective instrumentation is _very_ experimental. Do you want to describe a little more about your use-case?  How are you deciding what to instrument?

**Comment by jianyu-m** [comment]
I am planing to apply it to a big system, so I would like to try if instrument in only a critical component would help decrease the overhead.

**Comment by jon-bell** [comment]
The problem with this is you need to also find all code that is called by that critical component - if some code is passed data by that critical component, and then returns data to that critical component, you need to track through it. In my preliminary evaluations, by the time that you conduct that static analysis in a way that guarantees that you won't accidentally drop taint tags on something that you shouldn't, you end up tracking tags still on most things. This was with some testing on the dacapo set of macro benchmarks - maybe things would be different on your workloads though. What is performance like on your workloads without selective instrumentation?

The LazyArrays ended up being a significant improvement in overhead that came out of the selective instrumentation work - and on their own (those optimizations will occur regardless of if you use selective instrumentation now) can cause some pretty significant performance increases depending on the application.

**Comment by jianyu-m** [comment]
It do needs some effort to guarantee safety in that situation, so it is just a experiment. With LazyArrays, the performance is much better, but I just want to see how well it will work in selective instrument. Anyway, thanks for your answer.

**Comment by jon-bell** [comment]
OK! Let me know if you have any more problems then.
