### ISSUE TITLE
Error in Adding taint to Object de-serialized from file

### ISSUE THREAD

**Issue by jianyu-m** [Programming-Systems-Lab/phosphor#41]
Hello,

I came across a error when adding taint to a object de-serialized from file. The code is
```
class TestClass implements Serializable {
    int[] a = new int[3];
}

public class Hello {

    static public void main(String[] args) {
        TestClass c = new TestClass();
        ObjectOutputStream s = null;
        try {
            s = new ObjectOutputStream(new FileOutputStream("a.out"));
            s.writeObject(c);
            s.close();
        } catch (IOException e) {

        }

        try {
            TestClass k = (TestClass) new ObjectInputStream(new FileInputStream("a.out")).readObject();
            System.out.println(k.a);
            Tainter.taintedIntArray(k.a, 3);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
}
```
The code return a NullPointerException, and I found out that it is likely that the taint of the object(The LazyIntArrayIntTags of filed a in object TestClass is not properly initialized). The problem exists for object with array fields. I am wondering if you have the idea of how to resolve this?

Thanks in advance.

**Comment by jon-bell** [comment]
Hi Jinyu,
Just wanted to let you know I saw this and took a look. I should have a quick patch in the next few days - I am pretty busy this week.

Jon

**Comment by jon-bell** [comment]
This is going to be a little more complicated than I expected. In the meantime, reverting to an older version (before the lazy taint array initialization) should help - like aa122f9ec38c2804f909f9604f3f9796e94e020a

**Comment by jianyu-m** [comment]
Thanks for your help, I will have a try.

**Comment by jon-bell** [comment]
FYI - I have this seemingly working now with int tags (as of c35e6c7), but there is something weird going on with the object tagging and it is going to take an even more complicated fix.

**Comment by jon-bell** [comment]
Thanks again for your patience - things got really stacked up around here during the run-up to the OOPSLA deadline this year. This should be all set now, and there are now 2 regression test cases (for int and obj tags) for this issue.

**Comment by jianyu-m** [comment]
Thanks for fixing the problem. Previously I have modified jdk to solve the problem, as I find it time consuming to understand all the code. Anyway, thank you and wish you have a good luck in OOPSLA.
