### ISSUE TITLE
Missing Annotations

### ISSUE THREAD

**Issue by jsinglet** [Programming-Systems-Lab/phosphor#46]
It appears that phosphor is causing issues with retrieving annotations during reflection. 

Small example:

```java
public class ScanningExample {

	public static void main(String[] args) {

		Method[] mz = MyClass.class.getMethods();
		for(Method m : mz){
			if(m.isAnnotationPresent(MyAnnotation.class)){
				System.out.println("OK!");
			}
		}
		
	}

}

```

```java
public class MyClass {
	
	@MyAnnotation("test")                    
	public static boolean method() 
	{		
           return true;
	}
}
```

At times this will result in a stack trace (DuplicateAnnotationError) and other times it will just have a empty set of annotations if one requests the annotations on the method. 

Running this on a NON-Phophor JVM results in the above code printing "OK"

**Comment by jon-bell** [comment]
Thanks. Looks like there was a bug in TypeAnnotation handling (note that your sample annotation applies to the method return as well) - should be all set now.
